name: binder_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.2.4
  - pip
  - pip:
      - tensorflow==2.11.0
      - keras==2.11.0
      - astropy==4.2.1
      - numpy==1.23.5
      - scipy==1.9.1
      - scikit-learn==1.1.3
      - scikit-image==0.19.3
      - matplotlib==3.6.2
      - opencv-python
